extends:
  - eslint:recommended
  - prettier

env:
  es6: true
  node: true

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  no-console: off
  no-unused-vars: error
  no-undef: error
  prefer-const: error
  no-var: error

overrides:
  - files: "*.ts"
    parser: "@typescript-eslint/parser"
    plugins:
      - "@typescript-eslint"
    extends:
      - "plugin:@typescript-eslint/recommended"
    rules:
      "@typescript-eslint/no-unused-vars": error
      "@typescript-eslint/explicit-function-return-type": off
      "@typescript-eslint/no-explicit-any": warn