[package]
name = "minicache"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.48.0", features = ["full"]}

[dev-dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }
sysinfo = "0.37.2"

[[bench]]
name = "minicache_benchmark"
harness = false
